# -*- makefile -*- : Force emacs to use Makefile mode

# Specify EFI image builder
#
ELF2EFI		= $(ELF2EFI64)

# Specify EFI boot file
#
EFI_BOOT_FILE	= bootaa64.efi

# Include generic EFI Makefile
#
MAKEDEPS	+= arch/arm/Makefile.efi
include arch/arm/Makefile.efi
