# -*- makefile -*- : Force emacs to use Makefile mode

# Use %rip-relative addressing wherever possible.
#
CFLAGS		+= -fpie

# EFI probably doesn't guarantee us a red zone, so let's not rely on it.
#
CFLAGS		+= -mno-red-zone

# Specify EFI image builder
#
ELF2EFI		= $(ELF2EFI64)

# Specify EFI boot file
#
EFI_BOOT_FILE	= bootx64.efi

# Include generic EFI Makefile
#
MAKEDEPS	+= arch/x86/Makefile.efi
include arch/x86/Makefile.efi
