# -*- makefile -*- : Force emacs to use Makefile mode

# Specify EFI image builder
#
ELF2EFI		= $(ELF2EFI32)

# Use EFI ABI
#
CFLAGS		+= -malign-double

# Specify EFI boot file
#
EFI_BOOT_FILE	= bootia32.efi

# Include generic EFI Makefile
#
MAKEDEPS	+= arch/x86/Makefile.efi
include arch/x86/Makefile.efi
